##-----------Plugin made by abcalvin--------------

Confiscate: false

UpdateChecker: false

WorldBlockRemove: false

Worlds:
- world
- world_nether
- world_the_end

Blacklist:

Blacklist Placement:

Blacklist Break:

Blacklist Interaction:

Blacklist Pickup:

Blacklist Click:
