##-----------Plugin made by abcalvin--------------
Confiscate: false
UpdateChecker: true
Worlds:

Blacklist:

Blacklist Placement:

Blacklist Break:

Blacklist Interaction:

Blacklist Pickup:

Blacklist Click:
